name: Build Nugget

on:
  workflow_dispatch:

jobs:
  build-ubuntu-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Nugget repository
        run: git clone https://github.com/leminlimez/Nugget.git

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install upx libimobiledevice6 usbmuxd tree python3-tk 
          python3 -m pip install --upgrade pip nuitka
          pip install -r Nugget/requirements.txt

      - name: Build Ubuntu amd64
        run: |
          cd Nugget
          python3 -m nuitka \
          --standalone \
          --onefile \
          --include-data-dir=files/=./files \
          --enable-plugin=pyside6 \
          --include-package=zeroconf,pyimg4 \
          --include-module=zeroconf._utils.ipaddress,zeroconf._handlers.answers \
          --lto=yes \
          --include-package-data=pyimg4 \
          --output-filename=Nugget \
          main_app.py

      - name: Upx Nugget
        run: |
          cd Nugget/
          upx --lzma Nugget

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: Nugget_Ubuntu_amd64
          path: Nugget/Nugget
